# Generated by Django 6.1 on 2026-08-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('AUDITORIUM', 'Auditorium'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen')], max_length=20)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non-AC'), ('NA', 'Not Applicable')], default='NA', max_length=10)),
                ('title', models.CharField(help_text='Event/program name or purpose of booking.', max_length=200)),
                ('event_datetime', models.DateTimeField(help_text='Scheduled date/time of the program or stay start.')),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('seats_or_units', models.PositiveIntegerField(default=1, help_text='Seats (auditorium), rooms (hostel), or meal count (canteen).')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REBOOKING_REQUESTED', 'Rebooking Requested'), ('REBOOKED', 'Rebooked'), ('COMPLETED', 'Completed')], default='PENDING', max_length=25)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Refund Description Box: mandatory comprehensive reason attached permanently to the transaction ledger.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RebookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Logistical obstacles or reasons forcing the reschedule.')),
                ('proposed_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Principal Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('principal_remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_requests', to='bookings.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'PRINCIPAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rebookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
