# Generated by Django 6.1 on 2026-08-20 13:15

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_field_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[apps.accounts.validators.validate_phone_number]),
        ),
    ]
