# Generated by Django 6.1 on 2026-08-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g., Campus Doctor, First-Responder, Nurse.', max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('is_on_duty', models.BooleanField(default=True)),
                ('current_location', models.CharField(blank=True, help_text='Live location shared for dispatch.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qr_token', models.UUIDField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_logs', to=settings.AUTH_USER_MODEL)),
                ('dispatched_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_logs', to='emergency.medicalstaff')),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
    ]
