# Generated by Django 6.1 on 2026-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_id_card_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstaff',
            name='current_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
