# Generated by Django 6.1 on 2026-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_medicalstaff_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaff',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
